site:
  title: Red Hat OpenStack Platform - Break-fix Practice
  start_page: rhosp-networking-breakfix::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
